/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AanpakRouteImport } from './routes/aanpak'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as InspiratieRouteImport } from './routes/inspiratie'
import { Route as OfferteRouteImport } from './routes/offerte'
import { Route as ServiceRouteImport } from './routes/service'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AanpakRoute = AanpakRouteImport.update({
  id: '/aanpak',
  path: '/aanpak',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const InspiratieRoute = InspiratieRouteImport.update({
  id: '/inspiratie',
  path: '/inspiratie',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferteRoute = OfferteRouteImport.update({
  id: '/offerte',
  path: '/offerte',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aanpak': typeof AanpakRoute
  '/contact': typeof ContactRoute
  '/inspiratie': typeof InspiratieRoute
  '/offerte': typeof OfferteRoute
  '/service': typeof ServiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aanpak': typeof AanpakRoute
  '/contact': typeof ContactRoute
  '/inspiratie': typeof InspiratieRoute
  '/offerte': typeof OfferteRoute
  '/service': typeof ServiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aanpak': typeof AanpakRoute
  '/contact': typeof ContactRoute
  '/inspiratie': typeof InspiratieRoute
  '/offerte': typeof OfferteRoute
  '/service': typeof ServiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/aanpak' | '/contact' | '/inspiratie' | '/offerte' | '/service'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aanpak' | '/contact' | '/inspiratie' | '/offerte' | '/service'
  id:
    | '__root__'
    | '/'
    | '/aanpak'
    | '/contact'
    | '/inspiratie'
    | '/offerte'
    | '/service'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AanpakRoute: typeof AanpakRoute
  ContactRoute: typeof ContactRoute
  InspiratieRoute: typeof InspiratieRoute
  OfferteRoute: typeof OfferteRoute
  ServiceRoute: typeof ServiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aanpak': {
      id: '/aanpak'
      path: '/aanpak'
      fullPath: '/aanpak'
      preLoaderRoute: typeof AanpakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspiratie': {
      id: '/inspiratie'
      path: '/inspiratie'
      fullPath: '/inspiratie'
      preLoaderRoute: typeof InspiratieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offerte': {
      id: '/offerte'
      path: '/offerte'
      fullPath: '/offerte'
      preLoaderRoute: typeof OfferteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AanpakRoute: AanpakRoute,
  ContactRoute: ContactRoute,
  InspiratieRoute: InspiratieRoute,
  OfferteRoute: OfferteRoute,
  ServiceRoute: ServiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
